<?PHP


require_once('../config.php');
	/* Automatically Generated By X7 Chat 2 Installer :: 5:35:10 Aug 06, 2007 */
	$X7CHAT_CONFIG['DB_USERNAME'] = $DB_USERNAME;
	$X7CHAT_CONFIG['DB_PASSWORD'] = $DB_USERPASSWORD;
	$X7CHAT_CONFIG['DB_HOST'] = $DB_HOST;
	$X7CHAT_CONFIG['DB_NAME'] = $DB_NAME;
	$X7CHAT_CONFIG['DB_TYPE'] = $DB_TYPE;
	$prefix = "lchat_";
	$X7CHAT_CONFIG['AUTH_MODE'] = "md5";
	$X7CHAT_CONFIG['COOKIE_PATH'] = "/";
	$X7CHAT_CONFIG['USE_PCONNECT'] = 0;
	$X7CHAT_CONFIG['DISABLE_XUPDATER'] = 0;
	$X7CHAT_CONFIG['INSTALLED'] = 1;
	$X7CHATVERSION = "2.0.5";

	// These can be uncommented for debugging
	//$DEBUG_JAVASCRIPT = "";

	// MUSE Support
	// $MUSE_DB['current'] = 1;
	// $MUSE_DB['user_1'] = "";
	// $MUSE_DB['pass_1'] = "";
	// $MUSE_DB['user_2'] = "";
	// $MUSE_DB['pass_2'] = "";

?>
